steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-southeast1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/frontend:1.0', 'frontend/.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia-southeast1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/frontend:1.0' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'frontend'
  - '--image'
  - 'asia-southeast1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/frontend:1.0'
  - '--region'
  - 'asia-southeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'asia-southeast1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/frontend:1.0'