steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-southeast1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/marketplace:1.0', 'marketplace/.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia-southeast1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/marketplace:1.0' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'marketplace'
  - '--image'
  - 'asia-southeast1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/marketplace:1.0'
  - '--region'
  - 'asia-southeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  env:
  - 'PORT=8080'
  - 'REDIS_HOST=redis-19169.c60.us-west-1-2.ec2.cloud.redislabs.com'
  - 'REDIS_PORT=19169'
  - 'REDIS_USER=gazmin'
  secretEnv: 
  - REDIS_PASS
  - JWT_SECRET
availableSecrets:
  secretManager:
  - versionName: projects/232587127321/secrets/marketplace-redis-pass/versions/latest
    env: REDIS_PASS
  - versionName: projects/232587127321/secrets/marketplace-jwt-secret/versions/latest
    env: JWT_SECRET
images:
- 'asia-southeast1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/marketplace:1.0'
