steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/streetview:1.0', 'streetview/.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/streetview:1.0' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'streetview'
  - '--image'
  - 'us-central1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/streetview:1.0'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  env:
  - 'REDIS_HOST=redis-16438.c60.us-west-1-2.ec2.cloud.redislabs.com'
  - 'REDIS_PORT=16438'
  - 'REDIS_USER=gazmin'
  secretEnv: 
  - REDIS_PASS
availableSecrets:
  secretManager:
  - versionName: projects/essential-tower-359509/secrets/streetview-redis-pass
    env: REDIS_PASS
images:
- 'us-central1-docker.pkg.dev/essential-tower-359509/gazmin-docker-repo/streetview:1.0'